apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign-token
  labels:
    app: assign-token-app
  namespace: token-handler
spec:
  selector:
    matchLabels:
      app: assign-token-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: assign-token-app
    spec:
      containers:
      - name: assign-token-app
        image: conano/assign-token:latest
        env:
          - name: api-event-streaming-client-id
            valueFrom:
              secretKeyRef:
                name: assign-token-secret
                key: api_event_streaming_client_id 
          - name: service-name
            valueFrom:
              secretKeyRef:
                name: assign-token-secret
                key: service_name
          - name: api-assign-token
            valueFrom:
              secretKeyRef:
                name: assign-token-secret
                key: api_assign_token 
          - name: api-device
            valueFrom:
              secretKeyRef:
                name: assign-token-secret
                key: api_device 
          - name: api-add-device
            valueFrom:
              secretKeyRef:
                name: assign-token-secret
                key: api_add_device
          - name: api-cache
            valueFrom:
              secretKeyRef:
                name: assign-token-secret
                key: api_cache 
          - name: api-event-streaming-host
            valueFrom:
              secretKeyRef:
                name: assign-token-secret
                key: api_event_streaming_host 
          - name: api-db-url
            valueFrom:
              secretKeyRef:
                name: assign-token-secret
                key: api_db_url 
          - name: api-redis-host-local
            valueFrom:
              secretKeyRef:
                name: assign-token-secret
                key: api_redis_host_local        
        livenessProbe:
          exec:
            command:
              - python3.11
              - check_health.py
        imagePullPolicy: Always        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      